CREATE TABLE FILES (
    ID NUMBER,
    CONSTRAINT FILE_PK PRIMARY KEY(ID),
    NAME NVARCHAR2(10) NOT NULL,
    FORMAT NVARCHAR2(20) NOT NULL,
    FILE_SIZE NUMBER CHECK(FILE_SIZE > 0),
    STORAGE_ID NUMBER NOT NULL,
    CONSTRAINT STORAGE_FK FOREIGN KEY(STORAGE_ID) REFERENCES STORAGE(ID)
);

CREATE SEQUENCE FILE_ID_SEQ
    MINVALUE 1
    INCREMENT BY 1;
